---

- name: Set hostnames
  hosts: all
  sudo: true
  roles:
    - { role: ansible-hosts, iface: 'eth1' }
  tags:
    - hostname


# file: main.yml
- include: dbservers.yml
- include: schedulingservers.yml
- include: webservers.yml