---

# file: schedulingservers.yml

- name: Common tasks in all servers
  hosts: scheduling
  sudo: true
  roles:
    - common
  tags:
    - pre
    - common

- name: Install Redis
  hosts: scheduling
  roles:
    - scheduling-redis
  tags:
    - redis
    - scheduling