---


- debug: msg="blah {{virtualenv_path}}/bin"

- name: Create weblab instance
  # dummy server
  shell: "./weblab-admin.py create ~/example --http-server-port=8000"
  args:
    chdir: "{{virtualenv_path}}/bin"
  tags:
    - creation
    - weblab
    - instance
