---

- name: Redis installation
  apt:
    pkg: "{{ item }}"
    state: present
  sudo: True
  
  when: ansible_os_family == "Debian"
  with_items:
    - redis-server
  tags:
    - apt
    - installation
    - install
    - debian
    - redis


- name: Avoid storing anything in disk to reduce latency
  replace: dest=/etc/redis/redis.conf regexp="^{{ item }}$" replace="#{{ item }}"
  with_items:
    - "save 900 1"
    - "save 300 10"
    - "save 60 10000"
  sudo: True
  notify:
    - restart redis
  tags:
    - redis
    - configuration
    - file