---

python_interpreter: "{{virtualenv_weblab_path}}/bin/python"
weblab_installation_path: "/home/{{remote_user}}/example"

apache_conf_file: "{{weblab_installation_path}}/httpd/apache_weblab_generic.conf"