---


- name: Update repos
  apt: update_cache=yes
  when: ansible_os_family == "Debian"


# This should be done in each role, but I don't know why it does not work in other roles yet.
- name: Bulk dependency installation
  apt:
    pkg: "{{ item }}"
    state: present

  when: ansible_os_family == "Debian"
  with_items:
    - python-dev
    - python
    - python-pip
    - openjdk-6-jdk
    - git
    - apache2
    - apache2-mpm-worker
  tags:
    - apt
    - installation
    - install
    - debian