---

- name: Update repos
  apt: update_cache=yes
  when: ansible_os_family == "Debian"


# TODO This should be done in each role to avoid installing openjdk and other Weblab dependencies in the scheduler.
- name: Bulk dependency installation
  apt:
    pkg: "{{ item }}"
    state: present

  when: ansible_os_family == "Debian"
  with_items:
    - python-dev
    - python
    - python-pip
    - openjdk-6-jdk
    - git
  tags:
    - apt
    - installation
    - install
    - debian