---

- name: Install Git and Java
  apt:
    pkg: "{{ item }}"
    state: present
  sudo: True
  when: ansible_os_family == "Debian"
  with_items:
    - openjdk-7-jdk
    - git
  tags:
    - apt
    - installation
    - install
    - debian
    - git
    - java
    - openjdk


- name: Clone weblab
  git: repo={{ url }}
       dest={{ path }}
  tags:
    - git
    - clone
    - pull
    - weblab


- name: create virtualenv folder
  file: path=~/.virtualenvs
        state=directory
  tags:
    - virtualenv
    - create
    - folder


- name: Install app
  pip:
    virtualenv: "{{ virtualenv_weblab_path }}"
    # it will inherit packages from the global site-packages 
    virtualenv_site_packages: yes
    name: "{{ path }}"
    #chdir: ~/weblab
  tags:
    - virtualenv
    - pip
    - weblab


- name: Execution permissions for bin
  # I don't know why, activation scripts are now executable by default
  file: path="{{ virtualenv_weblab_path }}/bin/{{ item }}" mode=0754
  with_items:
    - activate
    - activate.csh
    - activate.fish
    - activate_this.py
  tags:
    - virtualenv
    - activate
    - permission