---

- name: MySQL installation
  apt:
    pkg: "{{ item }}"
    state: present
  sudo: True
  with_items:
    - mysql-server
    - python-mysqldb
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - installation
    - install
    - debian
    - mysql


- name: Create database for WebLab
  mysql_db: name="{{ db_name }}" state=present
  tags:
    - mysql
    - database
    - weblab
    - creation
    - create


- name: Create user for WebLab database
  mysql_user:
    state=present
    name="{{ db_user }}"
    password="{{ db_password }}"
    priv="{{ db_name }}.*:ALL"
    host="%" # any host, to ease different configurations, it should probably be restricted
  tags:
    - mysql
    - user
    - weblab
    - creation
    - create


- name: Serve to other machines
  replace: dest=/etc/mysql/my.cnf regexp="^bind-address\s*=\s*127.0.0.1$" replace="bind-address = 0.0.0.0"
  sudo: True
  tags:
    - mysql
    - configuration
    - file
  notify:
    - restart mysql